services:
  build:
    container_name: hinatsuki_build
    platform: linux/amd64
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /build
    privileged: true
    tty: true
